config/routes.rb
Rails.application.routes.draw do
  root "pictures#index"
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: {message: "空白以外の文字を入力して下さい(>_<)"}, length: { maximum: 30 }
  validates :email, presence: {message: "空白以外の文字を入力して下さい(>_<)"}, length: { maximum: 255}
  validates :password, length: { minimum: 6 }
    
  has_secure_password
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private
  
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :are_you_current_user?, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: "投稿でけた👍"
      else
        render :new
      end
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
  end

  def show
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "編集オッケー🙆"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"消せた(´ω｀)b"
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def are_you_current_user?
    unless @picture.user_id == current_user.id
      redirect_to pictures_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/pitures_helper.rb
module PituresHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendCircle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <header>
        <h1><%= link_to "Hand-magazine", pictures_path %></h1>
      </header>
      <table class="all_link">
        <tr>
          <% if logged_in? %>
            <td><%= link_to "Profile", user_path(current_user.id) %> | </td>
            <td><%= link_to "Logout", session_path(current_user.id), method: :delete %></td>
          <% else %>
            <td><%= link_to "Sign up", new_user_path %> | </td>
            <td><%= link_to "Login", new_session_path %></td>
          <% end %>
        </tr>
      </table>
      <br>
      <div>
        <% flash.each do |key, value| %>
          <h3><%= content_tag(:div, value, class: "#{key}") %><h3>
        <% end %>

        <%= yield %>
      </div>
      <br>
      <br>
      <footer>
        <%= link_to "ハンドマガジン TOP", pictures_path %>
      </footer>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :画像を選んでね %>
    <%= image_tag(picture.image.url) if picture.image && picture.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
    <br>
    <br>
    <%= f.label :一言添えて %>
    <%= f.text_area :content %>
  </div>
  <br>
  <% if @picture.id.present? %>
    <%= f.submit :修正できた？ %>
  <% else %>
    <%= f.submit :投稿じゃー！ %>
  <% end %>
<% end %>

app/views/pictures/confirm.html.erb
<h3>間違えとらん？</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |f| %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= f.hidden_field :image_cache %>
  <p>一言:<%= @picture.content %></p>
  <%= f.hidden_field :content %>
  <%= f.submit "完っ璧！" %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |f| %>
  <%= f.hidden_field :image_cache %>
  <%= f.hidden_field :content %>
  <%= f.submit "やっぱ書き直す", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集編集！</h2>
<%= render 'form', picture: @picture %>

app/views/pictures/index.html.erb
<h1>最新投稿！！</h1>

<table>
  <tr>
    <th>投稿者さん</th>
    <th>画像</th>
    <th>コメント</th>
  </tr>
  <% @pictures.each do |picture| %>
    <tr>
      <td><%= picture.user.name %></td>
      <td><%= image_tag(picture.image.url) if picture.image && picture.image.url %></td>
      <td><%= picture.content %></td>
      <td><%= link_to '確認', picture_path(picture.id) %></td>
      <% if picture.user_id == current_user.id %>
        <td><%= link_to '書き直し', edit_picture_path(picture.id) %></td>
        <td><%= link_to '消す', picture_path(picture.id), method: :delete, data: {confirm: '本当に消して良かですか？(>_<)'} %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "あなたの今を共有しよう！", new_picture_path %>

app/views/pictures/new.html.erb
<h2>投稿しましょう</h2>
<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<h3>確認がめん</h3>

<br>
<p>　画　像　: <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
<br>
<p>添えた一言: <%= @picture.content %></p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this<%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<br>
<%= link_to "あなたの今を共有しよう！", new_picture_path %>